RewriteLog  c:\temp\iirfLog.out
#RewriteLogLevel 5
#StatusInquiry ON /iirf

# MaxMatchCount
#
# Specifies the maximum number of sub-expression matches to
# capture for a single pattern. This specifies the size of the
# array in the C module.  If you have a pattern with more than
# the default number of matches, set this number.
#
# The default is 10. 

MaxMatchCount 10

# 
# RULES
# 

# Static content
RewriteRule ^/css/(.*)\.([0-9]{14})\.css$  /css/$1.css		[NC,L]
RewriteRule ^/js/(.*)\.([0-9]{14})\.js$  /js/$1.js		[NC,L]
RewriteRule ^/img/(.*)\.([0-9]{14})\.(gif|ico|jpg|png|svg)$  /img/$1.$3		[NC,L]

# Uncomment next two lines to take website offline
#RewriteCond %{REQUEST_URI} !/(img|js|css)/
#RewriteRule ^.*$    /offline.asp    [NC,L]

# Remove index.asp and/or .asp from URL's
RedirectRule ^(.*)index\.asp$    $1    [NC,L,QSA]

# Events and viewing photos
RewriteRule ^/event/([^\/]+)/([^\/^\?]+)/view/([0-9]+)    /viewpicture.asp?e=$1&s=$2&id=$3    [NC,L,QSA]
RewriteRule ^/event/([^\/]+)/view/([0-9]+)    /viewpicture.asp?e=$1&id=$2    [NC,L,QSA]
RewriteRule ^/event/([^\/^\?]+)/([^\/^\?]+)    /event.asp?e=$1&s=$2    [NC,L,QSA]
RewriteRule ^/event/([^\/^\?]+)    /event.asp?e=$1    [NC,L,QSA]

# Miscellaneous
RewriteRule ^/robots\.txt$    /robots-txt.asp    [NC,L]

# Search
RewriteRule ^/search-view    /search-viewpicture.asp    [NC,L,QSA]
RewriteRule ^/search    /search.asp    [NC,L,QSA]

# Basket
RewriteRule ^/basket/add/([0-9]+(,[0-9]+)*)\?size=([0-9]+)&xml=yes    /download-basket-update.asp?action=add&pictureid=$1&picturesizeid=$3&xml=yes    [NC,L]
RewriteRule ^/basket/remove/([0-9]+(,[0-9]+)*)\?size=([0-9]+)&xml=yes    /download-basket-update.asp?action=remove&pictureid=$1&picturesizeid=$3&xml=yes    [NC,L]
RewriteRule ^/basket/add/([0-9]+(,[0-9]+)*)\?size=([0-9]+)    /download-basket-update.asp?action=add&pictureid=$1&picturesizeid=$3    [NC,L]
RewriteRule ^/basket/remove/([0-9]+(,[0-9]+)*)\?size=([0-9]+)    /download-basket-update.asp?action=remove&pictureid=$1&picturesizeid=$3    [NC,L]
RewriteRule ^/basket/download/zip    /download-basket-zip.asp    [NC,L,QSA]
RewriteRule ^/basket/download    /download-basket.asp?download=zip    [NC,L]
RewriteRule ^/basket/clear    /download-basket-update.asp?action=clear    [NC,L]
RewriteRule ^/basket    /download-basket.asp    [NC,L,QSA]

# Pages
RewriteRule ^/login$    /login.asp    [NC,L,QSA]
RewriteRule ^/logout$    /logout.asp    [NC,L]
RewriteRule ^/account/disabled$    /account-disabled.asp    [NC,L]
RewriteRule ^/account/expired$    /account-expired.asp    [NC,L]
RewriteRule ^/downloadlimit$    /downloadlimit.asp    [NC,L]
RewriteRule ^/offline$    /offline.asp    [NC,L]

# Picture Download
RewriteRule ^/pictures/(.+)    /download-picture.asp?filename=$1    [NC,L]

# Admin
RewriteRule ^/admin/toggle-exclusive-group/([0-9]+)    /admin/toggle-exclusive-group.asp?pictureid=$1    [NC,L,QSA]
RewriteRule ^/admin/toggle-picture-status/([0-9]+)    /admin/toggle-picture-status.asp?pictureid=$1    [NC,L,QSA]
RewriteRule ^/admin/get-exclusive-groups/([0-9]+)    /admin/get-exclusive-groups.asp?pictureid=$1    [NC,L,QSA]
RewriteRule ^/admin/set-exclusive-groups/([0-9]+(,[0-9]+)*)    /admin/set-exclusive-groups.asp?pictureids=$1    [NC,L,QSA]
